### ISSUE TITLE
مشکل در انتقال یوزر ها 

### ISSUE THREAD

**Issue by Habib1385** [ItsAML/X-Ui-to-Marzban#1]
سلام 
خسته نباشید 
موقع انتقال یوزر از x-ui به مرزبان 
با علامت "." , "@" مشکل داره 
لطفا بررسی کنید و آپدیت کنید 
ممنون از شما

**Comment by Habib1385** [comment]
همچنین با ایموجی ها 
در واقع مرزبان اجازه استفاده رو نمیده 
ولی در x-ui فعال هستند

**Comment by ItsAML** [comment]
سلام بصورت ریجکس به اسکریپت اضافه شد
