### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by karbob01** [ItsAML/X-Ui-to-Marzban#4]
Number of Users: 142
*********
Traceback (most recent call last):
  File "main.py", line 417, in <module>
    user_data = get_x_inbounds_with_uuid(X_SESSION)
  File "main.py", line 170, in get_x_inbounds_with_uuid
    uuid_result = uuid["id"]
KeyError: 'id'

**Comment by ItsAML** [comment]
سلام، مشخصات x-ui رو داخل تلگرام برام بفرستید بررسی کنم، توی بحث گرفتن uuid از x-ui ظاهرا به مشکل خورده باید چک کنم ببینم بعد اپدیت پنل مقدارش عوض شده یا مشکل از جای دیگه ست

@YoAML
